/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model_2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model_2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-102.97, 14.019, -22.926]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone022L} />
        <primitive object={nodes.Bone023L} />
        <primitive object={nodes.Bone022R} />
        <primitive object={nodes.Bone023R} />
        <skinnedMesh geometry={nodes.model_template_1002.geometry} material={nodes.model_template_1002.material} skeleton={nodes.model_template_1002.skeleton} />
      </group>
      <group position={[-85.893, 13.905, -32.539]} rotation={[0, 0.441, 0]}>
        <primitive object={nodes.Bone_1} />
        <primitive object={nodes.Bone022L_1} />
        <primitive object={nodes.Bone023L_1} />
        <primitive object={nodes.Bone022R_1} />
        <primitive object={nodes.Bone023R_1} />
        <skinnedMesh geometry={nodes.body_2.geometry} material={nodes.body_2.material} skeleton={nodes.body_2.skeleton} />
      </group>
      <group position={[-116.233, 14.145, -34.014]} rotation={[0, -0.458, 0]}>
        <primitive object={nodes.Bone_2} />
        <primitive object={nodes.Bone022L_2} />
        <primitive object={nodes.Bone023L_2} />
        <primitive object={nodes.Bone022R_2} />
        <primitive object={nodes.Bone023R_2} />
        <skinnedMesh geometry={nodes.body_3.geometry} material={nodes.body_3.material} skeleton={nodes.body_3.skeleton} />
      </group>
      <mesh geometry={nodes.posesocle.geometry} material={nodes.posesocle.material} position={[-111.254, 6.995, -30.365]} />
      <mesh geometry={nodes.armring.geometry} material={nodes.armring.material} position={[-101.768, 15.058, -23.207]} rotation={[0, 0, -1.187]} />
      <mesh geometry={nodes.belt.geometry} material={nodes.belt.material} position={[-102.945, 13.803, -22.992]} />
      <mesh geometry={nodes.head.geometry} material={nodes.head.material} position={[-102.997, 17.067, -22.979]} />
      <mesh geometry={nodes.neck.geometry} material={nodes.neck.material} position={[-103.009, 16.619, -23.148]} />
      <mesh geometry={nodes.pose.geometry} material={nodes.pose.material} position={[-102.933, 9.325, -22.507]} />
      <mesh geometry={nodes.pose_2.geometry} material={nodes.pose_2.material} position={[-85.816, 9.325, -32.437]} rotation={[0, 0.441, 0]} />
      <mesh geometry={nodes.head_2.geometry} material={nodes.head_2.material} position={[-85.836, 16.801, -32.316]} rotation={[0, 0.441, 0]} scale={[0.75, 1, 1]} />
      <mesh geometry={nodes.wing_2.geometry} material={nodes.wing_2.material} position={[-85.989, 15.189, -32.716]} rotation={[0, 0.441, 0]} />
      <mesh geometry={nodes.head__3.geometry} material={nodes.head__3.material} position={[-116.319, 17.671, -33.977]} rotation={[0, -0.458, 0]} />
      <mesh geometry={nodes.tail_3.geometry} material={nodes.tail_3.material} position={[-115.664, 13.296, -35.091]} rotation={[-Math.PI / 2, 0, -0.458]} />
      <mesh geometry={nodes.belt_3.geometry} material={nodes.belt_3.material} position={[-116.491, 13.211, -33.477]} rotation={[-0.248, -0.446, -0.109]} />
      <mesh geometry={nodes.pose_3.geometry} material={nodes.pose_3.material} position={[-116.575, 9.413, -33.249]} rotation={[0, -0.458, 0]} />
      <mesh geometry={nodes.recade_2.geometry} material={nodes.recade_2.material} position={[35.388, 18.062, 5.282]} rotation={[-1.938, -0.085, -3.072]} />
      <mesh geometry={nodes.recade_1.geometry} material={nodes.recade_1.material} position={[-14.415, 17.8, -38.974]} rotation={[-1.527, -0.368, -1.555]} />
      <mesh geometry={nodes.recade_3.geometry} material={nodes.recade_3.material} position={[32.329, 18.549, -33.228]} rotation={[-1.814, -0.294, -2.366]} />
      <mesh geometry={nodes.recadeGlass_2.geometry} material={nodes.recadeGlass_2.material} position={[34.947, 18.358, 2.968]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.recadeGlass_3.geometry} material={nodes.recadeGlass_3.material} position={[29.844, 18.358, -34.896]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.recadesocle_2.geometry} material={nodes.recadesocle_2.material} position={[34.951, 8.543, 2.957]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.recadesocle_3.geometry} material={nodes.recadesocle_3.material} position={[29.839, 8.543, -34.906]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.recadevitrebar_2.geometry} material={nodes.recadevitrebar_2.material} position={[34.951, 21.254, 2.957]} rotation={[0, -1.571, 0]} />
      <mesh geometry={nodes.recadevitrebar_3.geometry} material={nodes.recadevitrebar_3.material} position={[29.839, 21.254, -34.906]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.recadesocle_1.geometry} material={nodes.recadesocle_1.material} position={[-16.259, 8.543, -38.083]} />
      <mesh geometry={nodes.recadevitrebar_1.geometry} material={nodes.recadevitrebar_1.material} position={[-16.259, 21.254, -38.083]} />
      <mesh geometry={nodes.recadeGlass_1.geometry} material={nodes.recadeGlass_1.material} position={[-16.248, 18.358, -38.08]} />
      <mesh geometry={nodes.wall.geometry} material={nodes.wall.material} position={[-40, 2.113, 0]} />
      <mesh geometry={nodes.ground.geometry} material={nodes.ground.material} position={[-40, 2.113, 0]} />
      <mesh geometry={nodes.groundwall.geometry} material={nodes.groundwall.material} position={[-40, 2.113, 0]} />
      <mesh geometry={nodes.plafond.geometry} material={nodes.plafond.material} position={[-78.154, 51.631, 0.058]} scale={0.3} />
      <mesh geometry={nodes.affiche_1.geometry} material={nodes.affiche_1.material} position={[-98.857, 21.273, -59.831]} />
      <mesh geometry={nodes.affiche_1_img.geometry} material={nodes.affiche_1_img.material} position={[-98.857, 21.273, -59.831]} />
      <mesh geometry={nodes.affiche_2_img.geometry} material={nodes.affiche_2_img.material} position={[-98.857, 21.273, -59.831]} />
      <mesh geometry={nodes.affiche_3_img.geometry} material={nodes.affiche_3_img.material} position={[-98.857, 21.273, -59.831]} />
      <mesh geometry={nodes.affiche_0_img.geometry} material={nodes.affiche_0_img.material} position={[-98.857, 21.273, -59.831]} />
      <mesh geometry={nodes.camlook_1.geometry} material={nodes.camlook_1.material} position={[-102.904, 18.02, -22.753]} />
      <mesh geometry={nodes.campose_1.geometry} material={nodes.campose_1.material} position={[-102.652, 8.281, 7.658]} />
      <mesh geometry={nodes.camlook_2.geometry} material={nodes.camlook_2.material} position={[19.115, 14.493, -23.502]} />
      <mesh geometry={nodes.campose_2.geometry} material={nodes.campose_2.material} position={[-11.732, 37.285, 7.658]} />
      <mesh geometry={nodes.camlook_0.geometry} material={nodes.camlook_0.material} position={[-187.442, 18.02, -31.179]} />
      <mesh geometry={nodes.campose_0.geometry} material={nodes.campose_0.material} position={[-187.19, 8.281, 7.658]} />
      <mesh geometry={nodes.bar2.geometry} material={nodes.bar2.material} position={[-187.659, 10.952, -21.185]} />
      <mesh geometry={nodes.desc.geometry} material={nodes.desc.material} position={[-195.346, 10.349, -29.344]} rotation={[-0.41, -0.508, -0.208]} />
      <mesh geometry={nodes.descselect.geometry} material={nodes.descselect.material} position={[-195.111, 10.234, -29.351]} rotation={[-0.41, -0.508, -0.208]} />
      <mesh geometry={nodes.pied2.geometry} material={nodes.pied2.material} position={[-187.544, 5.763, -36.913]} />
      <mesh geometry={nodes.trone.geometry} material={nodes.trone.material} position={[-187.437, 17.493, -35.568]} />
    </group>
  )
}

useGLTF.preload('/model_2.glb')
