/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/model_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model_1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pied.geometry} material={nodes.pied.material} position={[-41.033, 0.015, -27.952]} />
      <mesh geometry={nodes.glass.geometry} material={nodes.glass.material} position={[-41.179, 6.567, -28.002]} />
      <mesh geometry={nodes.bar.geometry} material={nodes.bar.material} position={[-41.049, 2.986, -25.205]} />
      <mesh geometry={nodes.glassbar.geometry} material={nodes.glassbar.material} position={[-41.029, 6.293, -27.971]} />
      <mesh geometry={nodes.scene.geometry} material={nodes.scene.material} position={[0.01, 0.044, 0.044]} />
      <mesh geometry={nodes.tamtam_1.geometry} material={nodes.tamtam_1.material} position={[13.529, 2.612, -22.799]} />
      <mesh geometry={nodes.tamtam_2.geometry} material={nodes.tamtam_2.material} position={[19.813, 5.632, -23.939]} scale={1.413} />
      <mesh geometry={nodes.tamtam_2_1.geometry} material={nodes.tamtam_2_1.material} position={[7.293, 4.327, -26.362]} rotation={[0.972, -0.358, 0.475]} scale={1.413} />
      <mesh geometry={nodes.maskCube.geometry} material={nodes.maskCube.material} position={[-41.034, 6.114, -27.974]}>
        <mesh geometry={nodes.cap_new.geometry} material={nodes.cap_new.material} position={[0.007, 0.359, 0.019]} />
        <mesh geometry={nodes.ears_new.geometry} material={nodes.ears_new.material} position={[0.006, 0.03, -0.285]} />
        <mesh geometry={nodes.face_new.geometry} material={nodes.face_new.material} position={[0.006, -0.198, 0.095]} />
        <mesh geometry={nodes.front_new.geometry} material={nodes.front_new.material} position={[0.011, 0.53, 0.1]} rotation={[-0.083, 0, 0]} scale={0.797} />
      </mesh>
      <mesh geometry={nodes.plafond.geometry} material={nodes.plafond.material} position={[-0.127, 31.974, 0.044]} />
    </group>
  )
}

useGLTF.preload('/model_1.glb')
